add_library(swgproto STATIC
    src/AccountVersionMessage.cpp
    src/LoginClientToken.cpp
    src/LoginEnumCluster.cpp
    src/LoginClusterStatus.cpp
    src/EnumerateCharacterId.cpp
    src/ErrorMessage.cpp
    src/ClientIdMessage.cpp
    src/SelectCharacter.cpp
    src/ClientPermissionsMessage.cpp
    src/CmdStartScene.cpp
    src/CmdSceneReady.cpp
    src/ClientRandomNameRequestPacket.cpp
    src/ClientRandomNameResponse.cpp
    src/ClientCreateCharacter.cpp
    src/ClientCreateCharacterSuccess.cpp
    src/ClientCreateCharacterFailed.cpp
    src/BaselineEnvelope.cpp
    src/SceneCreateObjectByCrc.cpp
    src/SceneEndBaselines.cpp
    src/UpdateContainmentMessage.cpp
    src/UpdateCellPermissionMessage.cpp
    src/UpdatePvpStatusMessage.cpp
    src/ObjControllerMessage.cpp
    src/Int32DeltaContainer.cpp
    src/CreatureObjectBaseline1.cpp
    src/TangibleObjectBaseline3.cpp
    src/CreatureObjectBaseline3.cpp
    src/CreatureObjectDelta.cpp
    src/IntangibleObjectBaseline3.cpp
    src/PlayerObjectBaseline3.cpp
    src/PlayerObjectBaseline6.cpp
    src/PlayerObjectDelta.cpp
    src/SchemaEngine.cpp
    src/ByteDeltaContainer.cpp
    src/StringInt32Map.cpp
    src/PlayerQuestData.cpp
    src/WaypointEntry.cpp
    src/PlayerObjectBaseline8.cpp
    src/SchematicEntry.cpp
    src/PlayerObjectBaseline9.cpp
    src/UpdateTransformMessage.cpp
    src/UpdateTransformWithParentMessage.cpp
    src/Animation.cpp
    src/PostureMessage.cpp
    src/DataTransform.cpp
    src/DataTransformWithParent.cpp
    src/ShowFlyText.cpp
    src/CommandQueueRemove.cpp
    src/ObjControllerDispatcher.cpp
    src/ObjectStateDispatcher.cpp
    src/Uint64DeltaContainer.cpp
    src/TangibleObjectBaseline6.cpp
    src/CreatureObjectBaseline6.cpp
    src/WearableEntry.cpp
    src/SkillModEntry.cpp
    src/MissionObjectEntry.cpp
    src/CreatureObjectBaseline4.cpp
    src/InstallationObjectBaseline3.cpp
    src/CellObjectBaseline3.cpp
    src/CellObjectBaseline6.cpp
    src/GuildObjectBaseline3.cpp
    src/GuildObjectBaseline6.cpp
    src/ChatSystemMessage.cpp
    src/CommandQueueEnqueue.cpp
    src/ObjectMenuSelect.cpp
    src/ResourceContainerBaseline3.cpp
    src/ResourceContainerBaseline6.cpp
    src/FactoryCrateBaseline3.cpp
    src/FactoryCrateBaseline6.cpp
    src/StaticObjectBaseline3.cpp
    src/StaticObjectBaseline6.cpp
    src/GroupObjectEntry.cpp
    src/GroupObjectBaseline3.cpp
    src/GroupObjectBaseline6.cpp
    src/GroupObjectDelta6.cpp
    src/HarvesterHopperEntry.cpp
    src/HarvesterObjectBaseline7.cpp
    src/HarvesterObjectDelta7.cpp
    src/WeaponRanges.cpp
    src/SpatialChat.cpp
    src/CommandQueueAdd.cpp
    src/Emote.cpp
    src/Flourish.cpp
    src/Buffs.cpp
    src/StartingLocationListMessage.cpp
    src/CombatSpam.cpp
    src/HarvesterResourceDataMessage.cpp
    src/SceneDestroyObject.cpp
    src/ObjectMenuResponse.cpp
)
add_library(swgproto::swgproto ALIAS swgproto)

target_include_directories(swgproto PUBLIC include)
target_link_libraries(swgproto PUBLIC soe::soe)
